  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
  
 
 [[main]]
  name = "Resume"
  weight = 200
  identifier = "resume"
  url = "https://drive.google.com/file/d/1r4cP3hlAfRNoCy4HYqT1rG_8SrXztR3T/view?usp=sharing"

  [[main]]
  name = "Blogs"
  weight = 200
  identifier = "blogs"
  url = "/blogs/"


  [[main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"

  [[main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

